apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\skaffold\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: service-three
  name: service-three
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8082
  selector:
    io.kompose.service: service-three
status:
  loadBalancer: {}
