apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\skaffold\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: service-three
  name: service-three
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-three
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\skaffold\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: service-three
    spec:
      containers:
        - image: vishalsvisual/service-three:latest
          imagePullPolicy: IfNotPresent
          name: service-three
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
